defmodule Mix.Tasks.AxonOnnx.Coverage do
  @shortdoc "Re-runs the ONNX corpus and regenerates COVERAGE.md"
  @moduledoc """
  Walks the materialised ONNX backend corpus (`test/cases/`), runs every case
  through `AxonOnnx.Coverage.run_case/1`, compares each to the registry, and
  writes a summary table to `COVERAGE.md`.

  This is a developer feedback loop, not a CI gate. CI consumes the
  `AxonOnnx.CoverageTest` ExUnit module instead — it has the same assertions
  but emits a per-case test failure when the registry drifts from reality.

  Run via:

      MIX_ENV=test mix axon_onnx.coverage

  The `MIX_ENV=test` prefix is important because the corpus is materialised in
  the test environment and `:exla` is a test-only dependency.

  Options:

    * `--category <name>` — restrict to one category (e.g. `node`,
      `pytorch-converted`). May be passed multiple times.
    * `--write false` — print the summary table to stdout but do not write
      `COVERAGE.md`.
  """
  use Mix.Task

  alias AxonOnnx.Coverage

  @impl Mix.Task
  def run(argv) do
    {opts, _, _} =
      OptionParser.parse(argv,
        strict: [category: :keep, write: :string],
        aliases: [c: :category]
      )

    categories = Keyword.get_values(opts, :category)
    write? = Keyword.get(opts, :write, "true") != "false"

    Mix.Task.run("app.start")

    cases =
      Coverage.discover()
      |> Enum.filter(fn entry ->
        categories == [] or entry.category in categories
      end)

    if cases == [] do
      Mix.shell().info("No cases discovered under #{Coverage.cases_root()}/. " <>
        "Run `mix test` once to materialise the corpus.")
      :ok
    else
      results = Enum.map(cases, &classify/1)
      report = render_report(results)

      if write? do
        File.write!("COVERAGE.md", report)
        Mix.shell().info("Wrote COVERAGE.md (#{length(results)} cases).")
      else
        Mix.shell().info(report)
      end
    end
  end

  defp classify(entry) do
    run_result = Coverage.run_case(entry)
    expected = Coverage.expected_status(entry)
    note = Coverage.note(entry)
    %{op_types: op_types, opset: opset} = Coverage.inspect_model(entry)

    classification =
      case {expected, run_result} do
        {:passing, :ok} -> :passing
        {:passing, {:error, _}} -> :regression
        {:unsupported, :ok} -> :newly_passing
        {:unsupported, {:error, _}} -> :unsupported
        {:known_bug, :ok} -> :newly_passing
        {:known_bug, {:error, _}} -> :known_bug
      end

    %{
      category: entry.category,
      name: entry.name,
      expected: expected,
      classification: classification,
      run_result: run_result,
      note: note,
      op_types: op_types,
      opset: opset
    }
  end

  defp render_report(results) do
    total = length(results)
    counts = Enum.frequencies_by(results, & &1.classification)

    summary_rows =
      for status <- [:passing, :unsupported, :known_bug, :newly_passing, :regression] do
        count = Map.get(counts, status, 0)
        pct = if total > 0, do: Float.round(100 * count / total, 1), else: 0.0
        "| #{status} | #{count} | #{pct}% |"
      end
      |> Enum.join("\n")

    per_category =
      results
      |> Enum.group_by(& &1.category)
      |> Enum.sort()
      |> Enum.map(fn {cat, items} -> per_category_section(cat, items) end)
      |> Enum.join("\n\n")

    per_op = render_per_op(results)
    registry_drift = render_drift(results)

    """
    # ONNX Coverage

    Generated by `mix axon_onnx.coverage`. Regenerate whenever the registry or
    operator dispatch changes — do not edit by hand.

    Total cases: **#{total}**

    | Classification | Count | % of total |
    |---|---|---|
    #{summary_rows}

    ## Per-category breakdown

    #{per_category}

    ## Per-operator breakdown

    Counts each case under every op_type that appears in its `model.onnx`.
    A case using N distinct ops contributes to N rows.

    #{per_op}

    #{registry_drift}
    """
  end

  defp per_category_section(category, items) do
    counts = Enum.frequencies_by(items, & &1.classification)
    total = length(items)
    line = "**#{category}** — #{total} cases"

    breakdown =
      for status <- [:passing, :unsupported, :known_bug, :newly_passing, :regression],
          count = Map.get(counts, status, 0),
          count > 0 do
        "- #{status}: #{count}"
      end
      |> Enum.join("\n")

    line <> "\n\n" <> breakdown
  end

  defp render_per_op(results) do
    per_op =
      results
      |> Enum.flat_map(fn r -> Enum.map(r.op_types, &{&1, r.classification}) end)
      |> Enum.group_by(fn {op, _} -> op end, fn {_, c} -> c end)
      |> Enum.map(fn {op, classes} ->
        counts = Enum.frequencies(classes)

        {op, length(classes), Map.get(counts, :passing, 0), Map.get(counts, :unsupported, 0),
         Map.get(counts, :known_bug, 0), Map.get(counts, :regression, 0),
         Map.get(counts, :newly_passing, 0)}
      end)
      |> Enum.sort_by(fn {op, _, _, _, _, _, _} -> op end)

    header = "| op_type | cases | passing | unsupported | known_bug | regression | newly_passing |"
    sep = "|---|---|---|---|---|---|---|"

    rows =
      per_op
      |> Enum.map(fn {op, total, p, u, k, r, n} ->
        "| #{op} | #{total} | #{p} | #{u} | #{k} | #{r} | #{n} |"
      end)
      |> Enum.join("\n")

    [header, sep, rows] |> Enum.join("\n")
  end

  defp render_drift(results) do
    newly_passing = Enum.filter(results, &(&1.classification == :newly_passing))
    regressions = Enum.filter(results, &(&1.classification == :regression))

    if newly_passing == [] and regressions == [] do
      ""
    else
      """
      ## Registry drift

      `mix axon_onnx.coverage` flagged these cases as drifting from
      `AxonOnnx.Coverage.Registry`. Update the registry to clear them.

      #{render_drift_section("Newly passing (promote in registry)", newly_passing)}
      #{render_drift_section("Regressions (was :passing, now failing)", regressions)}
      """
    end
  end

  defp render_drift_section(_title, []), do: ""

  defp render_drift_section(title, items) do
    rows =
      items
      |> Enum.sort_by(&{&1.category, &1.name})
      |> Enum.map(fn r ->
        reason =
          case r.run_result do
            :ok -> "(now passing)"
            {:error, reason} -> truncate(reason, 100)
          end

        "- `#{r.category}/#{r.name}` — #{reason}"
      end)
      |> Enum.join("\n")

    "### #{title}\n\n#{rows}\n"
  end

  defp truncate(s, n) when is_binary(s) and byte_size(s) <= n, do: s

  defp truncate(s, n) when is_binary(s) do
    binary_part(s, 0, n) <> "…"
  end

  defp truncate(other, n), do: other |> inspect() |> truncate(n)
end
